language: python
dist: trusty
sudo: false
install: pip install coveralls
script: make test
after_success: coveralls
cache:
    directories:
        - $HOME/.cache/pip
        - $HOME/.cache/pip-faster
        - $HOME/.cache/venv-update
        - $HOME/.pre-commit
